### ISSUE TITLE
Issue with "bundle exec rake publish_gem".

### ISSUE THREAD

**Issue by erichandsmith** [elastic/logstash-devutils#28]
Hello. I was following the instructions on [how to write a Logstash output plugin](https://www.elastic.co/guide/en/logstash/current/_how_to_write_a_logstash_output_plugin.html), and received the following error when executing "bundle exec rake publish_gem".

I'm building on Windows, and actually successfully built a couple plugins a few weeks ago. Could you please help me out?  Thank you.

```
C:\Projects\GitHub\elastic\logstash-output-https>bundle exec rake publish_gem --trace
io/console not supported; tty will not be manipulated
io/console not supported; tty will not be manipulated
** Invoke publish_gem (first_time)
** Execute publish_gem
rake aborted!
IOError: Cannot run program "gem" (in directory "C:\Projects\GitHub\elastic\logstash-output-https"): CreateProcess error=2, The system cannot find the file specified
org/jruby/RubyIO.java:4386:in `popen3'
C:/jruby/lib/ruby/1.9/open3.rb:74:in `popen3'
C:/jruby/lib/ruby/gems/shared/gems/logstash-devutils-0.0.13-java/lib/logstash/devutils/rake/publish.rake:11:in `execute'
C:/jruby/lib/ruby/gems/shared/gems/gem_publisher-1.5.0/lib/gem_publisher/builder.rb:10:in `build'
C:/jruby/lib/ruby/gems/shared/gems/gem_publisher-1.5.0/lib/gem_publisher/publisher.rb:30:in `publish_if_updated'
C:/jruby/lib/ruby/gems/shared/gems/gem_publisher-1.5.0/lib/gem_publisher.rb:26:in `publish_if_updated'
C:/jruby/lib/ruby/gems/shared/gems/logstash-devutils-0.0.13-java/lib/logstash/devutils/rake/publish.rake:27:in `(root)'
org/jruby/RubyProc.java:271:in `call'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:238:in `execute'
org/jruby/RubyArray.java:1613:in `each'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
C:/jruby/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
C:/jruby/lib/ruby/gems/shared/gems/rake-10.4.2/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
C:\jruby\bin\rake:23:in `(root)'
Tasks: TOP => publish_gem
```

**Comment by erichandsmith** [comment]
I'll figure it out, but "gem" works from the command line, but not from "bundle exec rake publish_gem". Must be an environmental variable thing.

**Comment by apenvern** [comment]
Hello I have the same problem on Windows. How did you fix it ?
But on Ubuntu I haven't this problem.
